# Generated by Django 5.2 on 2025-07-08 05:18

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', wagtail.fields.RichTextField()),
                ('is_active', models.BooleanField(default=False, help_text='Only one alert can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelAlertPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Page title or tagline for hero section', max_length=255)),
                ('sub_title', models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='A description of the page.')),
                ('hero_image', models.ForeignKey(help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('svg_icon', models.ForeignKey(blank=True, help_text='SVG icon for the page, used in other sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Travel Alerts Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
