# Generated by Django 5.2 on 2025-07-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alert',
            new_name='TravelAlert',
        ),
    ]
