# Generated by Django 5.2 on 2025-07-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_rename_alert_travelalert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelalert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Travel Alert', 'verbose_name_plural': 'Travel Alerts'},
        ),
    ]
