# Generated by Django 5.2 on 2025-04-30 23:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_destinationindexpage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Page title or tagline for hero section', max_length=255)),
                ('reasons_to_visit', wagtail.fields.StreamField([('section', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('core.blocks.TextBlock', (), {'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 1), ('image', 2), ('image_position', 3)]], {})})),
                ('travel_requirements', wagtail.fields.StreamField([('travel_requirement', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('core.blocks.TextBlock', (), {'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'features': ['link'], 'help_text': 'A link to the visa requirements', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('link', 2)]], {})})),
                ('hero_image', models.ForeignKey(blank=True, help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Destination Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Page title or tagline for hero section', max_length=255)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='A short description of the page')),
                ('hero_image', models.ForeignKey(blank=True, help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Flight Schedule Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SpecialsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Page title or tagline for hero section', max_length=255)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='A short description of the page')),
                ('hero_image', models.ForeignKey(blank=True, help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Specials Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WhereWeFly',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Page title or tagline for hero section', max_length=255)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='A short description of the page')),
                ('hero_image', models.ForeignKey(blank=True, help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Where We Fly Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
