# Generated by Django 5.2 on 2025-05-01 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_destination_flightschedule_specialsindexpage_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Page title or tagline for hero section', max_length=255)),
                ('departure_airport', models.CharField(blank=True, help_text='Departure airport for the route', max_length=255)),
                ('arrival_airport', models.CharField(blank=True, help_text='Arrival airport for the route', max_length=255)),
                ('departure_airport_code', models.CharField(blank=True, help_text='IATA code for the departure airport', max_length=3)),
                ('arrival_airport_code', models.CharField(blank=True, help_text='IATA code for the arrival airport', max_length=3)),
                ('country_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='explore.destination')),
                ('hero_image', models.ForeignKey(blank=True, help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Route Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
