# Generated by Django 5.2 on 2025-05-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='country_destination',
            new_name='destination_country',
        ),
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(blank=True, help_text='Name of Country for the destination', max_length=255),
        ),
    ]
