# Generated by Django 5.2 on 2025-05-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_rename_country_destination_route_destination_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
