# Generated by Django 5.2 on 2025-05-01 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_route_route_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='route_code',
            new_name='name',
        ),
    ]
