# Generated by Django 5.2 on 2025-05-01 03:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0007_rename_route_code_route_name'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.CharField(blank=True, help_text='Name of Country/Destination', max_length=255),
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Page title or tagline for hero section', max_length=255)),
                ('start_date', models.DateField(blank=True, help_text='Start date of the flight special', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date of the flight special', null=True)),
                ('terms_and_conditions', wagtail.fields.RichTextField(blank=True, help_text='Terms and conditions for the flight special')),
                ('hero_image', models.ForeignKey(blank=True, help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('routes', models.ManyToManyField(blank=True, help_text='Select routes associated with this special', related_name='specials', to='explore.route')),
            ],
            options={
                'verbose_name': 'Specials Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
