# Generated by Django 5.2 on 2025-05-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0008_alter_destination_country_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='routes',
            field=models.ManyToManyField(help_text='Select routes associated with this special', related_name='specials', to='explore.route'),
        ),
    ]
