# Generated by Django 5.2 on 2025-05-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explore", "0009_alter_special_routes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="special",
            old_name="routes",
            new_name="specials_routes",
        ),
    ]
