# Generated by Django 5.2 on 2025-05-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0011_rename_routes_special_specials_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='specials_routes',
        ),
        migrations.AddField(
            model_name='special',
            name='routes',
            field=models.ManyToManyField(help_text='Select one or more routes associated with this special (required)', related_name='specials', to='explore.route'),
        ),
    ]
