# Generated by Django 5.2 on 2025-05-01 08:34

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0012_remove_special_specials_routes_special_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='routes',
            field=modelcluster.fields.ParentalManyToManyField(related_name='specials', to='explore.route'),
        ),
    ]
