# Generated by Django 5.2 on 2025-05-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0013_alter_special_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
