# Generated by Django 5.2 on 2025-05-11 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0014_special_name'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wherewefly',
            name='domestic_routes',
            field=models.ForeignKey(blank=True, help_text='Image of your domestic routes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='wherewefly',
            name='international_routes',
            field=models.ForeignKey(blank=True, help_text='Image of your international routes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
