# Generated by Django 5.2 on 2025-05-13 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0015_wherewefly_domestic_routes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination_country',
            field=models.ForeignKey(blank=True, help_text='Destination country for the route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='explore.destination'),
        ),
    ]
