# Generated by Django 5.2 on 2025-05-13 08:31

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0016_alter_route_destination_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='specials',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select specials relevant to this destination', limit_choices_to='get_specials_limit_choices', related_name='destinations', to='explore.special'),
        ),
    ]
