# Generated by Django 5.2 on 2025-05-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0017_destination_specials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='specials',
        ),
    ]
