# Generated by Django 5.2 on 2025-05-13 08:48

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0018_remove_destination_specials'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='selected_specials',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select which specials to display for this destination', related_name='featured_destinations', to='explore.special'),
        ),
    ]
