# Generated by Django 5.2 on 2025-05-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0019_destination_selected_specials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='selected_specials',
        ),
    ]
