# Generated by Django 5.2 on 2025-05-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0020_remove_destination_selected_specials'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='name_full',
            field=models.CharField(blank=True, help_text='Full name of the route', max_length=255, null=True),
        ),
    ]
