# Generated by Django 5.2 on 2025-05-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0021_route_name_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
