# Generated by Django 5.2 on 2025-05-15 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0022_alter_route_name_alter_route_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_price', models.DecimalField(decimal_places=2, help_text='Starting price for this special on this route', max_digits=10)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_routes', to='explore.route')),
                ('special', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_routes', to='explore.special')),
            ],
            options={
                'verbose_name': 'Special Route',
                'unique_together': {('special', 'route')},
            },
        ),
    ]
