# Generated by Django 5.2 on 2025-05-15 07:38

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0023_specialroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialroute',
            name='route',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_routes', to='explore.route'),
        ),
        migrations.AlterField(
            model_name='specialroute',
            name='special',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_routes', to='explore.special'),
        ),
    ]
