# Generated by Django 5.2 on 2025-05-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0024_alter_specialroute_route_alter_specialroute_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='routes',
        ),
    ]
