# Generated by Django 5.2 on 2025-05-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0025_remove_special_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='special_code',
            field=models.CharField(blank=True, help_text='Unique ID for this flight special. This is used for tracking purposes.', max_length=50, null=True),
        ),
    ]
