# Generated by Django 5.2 on 2025-05-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0027_alter_special_special_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialroute',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', max_length=20),
        ),
    ]
