# Generated by Django 5.2 on 2025-05-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0028_specialroute_trip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialroute',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'One Way'), ('return_trip', 'Return Trip')], default='one_way', max_length=20),
        ),
    ]
