# Generated by Django 5.2 on 2025-05-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0029_alter_specialroute_trip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialroute',
            name='trip_type',
            field=models.CharField(choices=[('One Way', 'One Way'), ('Return', 'Return')], default='One Way', max_length=20),
        ),
    ]
