# Generated by Django 5.2 on 2025-05-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0030_alter_specialroute_trip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialroute',
            name='trip_type',
            field=models.CharField(choices=[('one way', 'One Way'), ('return', 'Return')], default='one way', max_length=20),
        ),
    ]
