# Generated by Django 5.2 on 2025-06-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0031_alter_specialroute_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='flight_scope',
            field=models.CharField(choices=[('international route', 'International Route'), ('domestic route', 'Domestic Route')], default='international route', max_length=20),
        ),
    ]
