# Generated by Django 5.2 on 2025-06-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0032_route_flight_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=255),
        ),
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=255),
        ),
        migrations.AddField(
            model_name='special',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='destinationindexpage',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='exploreindexpage',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='specialsindexpage',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='wherewefly',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=255),
        ),
    ]
