# Generated by Django 5.2 on 2025-06-11 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0033_destination_description_route_description_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='hero_image',
            field=models.ForeignKey(help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='destinationindexpage',
            name='hero_image',
            field=models.ForeignKey(help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='exploreindexpage',
            name='hero_image',
            field=models.ForeignKey(help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='hero_image',
            field=models.ForeignKey(help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='route',
            name='hero_image',
            field=models.ForeignKey(help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='special',
            name='hero_image',
            field=models.ForeignKey(help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='specialsindexpage',
            name='hero_image',
            field=models.ForeignKey(help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='wherewefly',
            name='hero_image',
            field=models.ForeignKey(help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
