# Generated by Django 5.2 on 2025-06-11 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0034_alter_destination_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.CharField(help_text='Name of Country/Destination', max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='arrival_airport',
            field=models.CharField(help_text='Arrival airport for the route', max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='arrival_airport_code',
            field=models.CharField(help_text='IATA code for the arrival airport', max_length=3),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_airport',
            field=models.CharField(help_text='Departure airport for the route', max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_airport_code',
            field=models.CharField(help_text='IATA code for the departure airport', max_length=3),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination_country',
            field=models.ForeignKey(help_text='Destination country for the route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='explore.destination'),
        ),
        migrations.AlterField(
            model_name='route',
            name='flight_scope',
            field=models.CharField(choices=[('international route', 'International Route'), ('domestic route', 'Domestic Route')], default='international route', help_text='Scope of the flight route (International or Domestic)', max_length=20),
        ),
        migrations.AlterField(
            model_name='special',
            name='end_date',
            field=models.DateField(help_text='End date of the flight special', null=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='special_code',
            field=models.CharField(help_text='Unique ID for this flight special. This is used for tracking purposes only.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='start_date',
            field=models.DateField(help_text='Start date of the flight special', null=True),
        ),
    ]
