# Generated by Django 5.2 on 2025-06-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0035_alter_destination_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='destinationindexpage',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='exploreindexpage',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='special',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='specialsindexpage',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='wherewefly',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=2000),
        ),
    ]
