# Generated by Django 5.2 on 2025-06-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0038_alter_destination_reasons_to_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='sub_title',
            field=models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='destinationindexpage',
            name='sub_title',
            field=models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='exploreindexpage',
            name='sub_title',
            field=models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='sub_title',
            field=models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='route',
            name='sub_title',
            field=models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='special',
            name='sub_title',
            field=models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='specialsindexpage',
            name='sub_title',
            field=models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='wherewefly',
            name='sub_title',
            field=models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100),
        ),
    ]
