# Generated by Django 5.2 on 2025-06-25 10:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0039_destination_sub_title_destinationindexpage_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short description of the page.'),
        ),
        migrations.AlterField(
            model_name='destinationindexpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short description of the page.'),
        ),
        migrations.AlterField(
            model_name='exploreindexpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short description of the page.'),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short description of the page.'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short description of the page.'),
        ),
        migrations.AlterField(
            model_name='special',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short description of the page.'),
        ),
        migrations.AlterField(
            model_name='specialsindexpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short description of the page.'),
        ),
        migrations.AlterField(
            model_name='wherewefly',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short description of the page.'),
        ),
    ]
