# Generated by Django 5.2 on 2025-06-30 08:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0040_alter_destination_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='discount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='special',
            name='flight_scope',
            field=models.CharField(choices=[('international routes', 'International Routes'), ('domestic routes', 'Domestic Routes')], default='international routes', max_length=20),
        ),
        migrations.AddField(
            model_name='special',
            name='travel_periods',
            field=wagtail.fields.StreamField([('travel_period', 2)], blank=True, block_lookup={0: ('wagtail.blocks.DateBlock', (), {'help_text': 'Start date of the period', 'required': True}), 1: ('wagtail.blocks.DateBlock', (), {'help_text': 'End date of the period', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('start_date', 0), ('end_date', 1)]], {})}, help_text='Periods during which this special is valid. Specify start and end dates.'),
        ),
        migrations.AddField(
            model_name='special',
            name='trip_type',
            field=models.CharField(choices=[('one way', 'One Way'), ('return', 'Return')], default='Return', help_text='Type of trip for this special (One Way or Return)', max_length=20),
        ),
    ]
