# Generated by Django 5.2 on 2025-06-30 09:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0041_special_discount_special_flight_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='travel_periods',
            field=wagtail.fields.StreamField([('travel_period', 0)], blank=True, block_lookup={0: ('wagtail.blocks.StructBlock', [[]], {})}, help_text='Periods during which this special is valid. Specify start and end dates.'),
        ),
    ]
