# Generated by Django 5.2 on 2025-06-30 09:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0042_alter_special_travel_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='travel_periods',
            field=wagtail.fields.StreamField([('travel_period', 2)], blank=True, block_lookup={0: ('wagtail.blocks.DateBlock', (), {'help_text': 'Start date of the period', 'required': True}), 1: ('wagtail.blocks.DateBlock', (), {'help_text': 'End date of the period', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('start_date', 0), ('end_date', 1)]], {})}, help_text='Periods during which this special is valid. Specify start and end dates.'),
        ),
    ]
