# Generated by Django 5.2 on 2025-06-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0043_alter_special_travel_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='booking_class',
            field=models.CharField(help_text='Class of booking for this flight special', max_length=20, null=True),
        ),
    ]
