# Generated by Django 5.2 on 2025-07-01 03:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0044_special_booking_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='sales_period',
            field=wagtail.fields.StreamField([('sales_period', 2)], blank=True, block_lookup={0: ('wagtail.blocks.DateBlock', (), {'help_text': 'Start date of the period', 'required': True}), 1: ('wagtail.blocks.DateBlock', (), {'help_text': 'End date of the period', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('start_date', 0), ('end_date', 1)]], {})}, help_text='Period during which this special is on sale. Specify a start and end date.'),
        ),
    ]
