# Generated by Django 5.2 on 2025-07-01 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0045_special_sales_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='sales_period',
        ),
    ]
