# Generated by Django 5.2 on 2025-07-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0046_remove_special_sales_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='booking_class',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='name',
            field=models.CharField(help_text='Name of this special.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='special_code',
            field=models.CharField(help_text='Unique ID for this flight special - used for tracking purposes only.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='trip_type',
            field=models.CharField(choices=[('one way', 'One Way'), ('return', 'Return')], default='Return', max_length=20),
        ),
    ]
