# Generated by Django 5.2 on 2025-07-01 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_svgimage_alter_genericpage_svg_icon_svgrendition'),
        ('explore', '0048_destination_svg_icon_destinationindexpage_svg_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='svg_icon',
            field=models.ForeignKey(blank=True, help_text='SVG icon for the page, used in other sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.svgimage'),
        ),
        migrations.AlterField(
            model_name='destinationindexpage',
            name='svg_icon',
            field=models.ForeignKey(blank=True, help_text='SVG icon for the page, used in other sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.svgimage'),
        ),
        migrations.AlterField(
            model_name='exploreindexpage',
            name='svg_icon',
            field=models.ForeignKey(blank=True, help_text='SVG icon for the page, used in other sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.svgimage'),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='svg_icon',
            field=models.ForeignKey(blank=True, help_text='SVG icon for the page, used in other sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.svgimage'),
        ),
        migrations.AlterField(
            model_name='route',
            name='svg_icon',
            field=models.ForeignKey(blank=True, help_text='SVG icon for the page, used in other sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.svgimage'),
        ),
        migrations.AlterField(
            model_name='special',
            name='svg_icon',
            field=models.ForeignKey(blank=True, help_text='SVG icon for the page, used in other sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.svgimage'),
        ),
        migrations.AlterField(
            model_name='specialsindexpage',
            name='svg_icon',
            field=models.ForeignKey(blank=True, help_text='SVG icon for the page, used in other sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.svgimage'),
        ),
        migrations.AlterField(
            model_name='wherewefly',
            name='svg_icon',
            field=models.ForeignKey(blank=True, help_text='SVG icon for the page, used in other sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.svgimage'),
        ),
    ]
