# Generated by Django 5.2 on 2025-07-01 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_delete_svgimage'),
        ('explore', '0050_alter_destination_svg_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialroute',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency for the starting price', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_routes', to='core.currency'),
        ),
    ]
