# Generated by Django 5.2 on 2025-07-01 10:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0051_specialroute_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A description of the page.'),
        ),
        migrations.AlterField(
            model_name='destinationindexpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A description of the page.'),
        ),
        migrations.AlterField(
            model_name='exploreindexpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A description of the page.'),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A description of the page.'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A description of the page.'),
        ),
        migrations.AlterField(
            model_name='special',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A description of the page.'),
        ),
        migrations.AlterField(
            model_name='specialsindexpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A description of the page.'),
        ),
        migrations.AlterField(
            model_name='wherewefly',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A description of the page.'),
        ),
    ]
