# Generated by Django 5.2 on 2025-07-02 04:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0052_alter_destination_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='travel_requirements',
            field=wagtail.fields.StreamField([('travel_requirement', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('core.blocks.TextBlock', (), {'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'features': ['link'], 'help_text': 'A link to the visa requirements', 'required': True}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'SVG icon for the travel requirement card', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('link', 2), ('svg_icon', 3)]], {})}),
        ),
    ]
