# Generated by Django 5.2 on 2025-07-15 05:34

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0053_alter_destination_travel_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which this route appears on the destination page')),
                ('destination', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_routes', to='explore.destination')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_rankings', to='explore.route')),
            ],
            options={
                'verbose_name': 'Destination Route Ranking',
                'verbose_name_plural': 'Destination Route Rankings',
                'ordering': ['display_order', 'id'],
                'unique_together': {('destination', 'route')},
            },
        ),
    ]
