# Generated by Django 5.2 on 2025-07-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0054_destinationroute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationroute',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Destination Route', 'verbose_name_plural': 'Destination Routes'},
        ),
        migrations.RenameField(
            model_name='destinationroute',
            old_name='display_order',
            new_name='sort_order',
        ),
    ]
