# Generated by Django 5.2 on 2025-07-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0055_alter_destinationroute_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationroute',
            options={'verbose_name': 'Destination Route', 'verbose_name_plural': 'Destination Routes'},
        ),
        migrations.AlterField(
            model_name='destinationroute',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
