# Generated by Django 5.2 on 2025-07-15 05:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0056_alter_destinationroute_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='reasons_to_visit',
            field=wagtail.fields.StreamField([('section', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('core.blocks.TextBlock', (), {'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 1), ('image', 2), ('image_position', 3)]], {})}),
        ),
    ]
