# Generated by Django 5.2 on 2025-07-15 22:13

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0057_alter_destination_reasons_to_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationroute',
            options={'ordering': ['sort_order'], 'verbose_name': 'Destination Route', 'verbose_name_plural': 'Destination Routes'},
        ),
        migrations.CreateModel(
            name='WhereWeFlyDomesticRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_we_fly_domestic_rankings', to='explore.route')),
                ('where_we_fly', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_domestic_routes', to='explore.wherewefly')),
            ],
            options={
                'verbose_name': 'Domestic Route',
                'verbose_name_plural': 'Domestic Routes',
                'ordering': ['sort_order'],
                'unique_together': {('where_we_fly', 'route')},
            },
        ),
        migrations.CreateModel(
            name='WhereWeFlyInternationalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_we_fly_international_rankings', to='explore.route')),
                ('where_we_fly', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_international_routes', to='explore.wherewefly')),
            ],
            options={
                'verbose_name': 'International Route',
                'verbose_name_plural': 'International Routes',
                'ordering': ['sort_order'],
                'unique_together': {('where_we_fly', 'route')},
            },
        ),
    ]
