# Generated by Django 5.2 on 2025-07-15 23:32

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0058_alter_destinationroute_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRelatedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('related_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_route_rankings', to='explore.route')),
                ('route', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_related_routes', to='explore.route')),
            ],
            options={
                'verbose_name': 'Related Route',
                'verbose_name_plural': 'Related Routes',
                'ordering': ['sort_order'],
                'unique_together': {('route', 'related_route')},
            },
        ),
    ]
