# Generated by Django manually to remove wagtail_color_panel references

from django.db import migrations
import wagtail.fields
import core.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0059_routerelatedroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='reasons_to_visit',
            field=wagtail.fields.StreamField([
                ('section', core.blocks.SectionBlock()),
            ], blank=True),
        ),
    ]