# Generated by Django 5.2 on 2025-08-04 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0059_routerelatedroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_airport_code', models.CharField(help_text='IATA code for the origin airport', max_length=3)),
                ('destination_airport_code', models.CharField(help_text='IATA code for the destination airport', max_length=3)),
                ('route_type', models.CharField(choices=[('direct', 'Direct'), ('connecting', 'Connecting')], help_text='Whether this is a direct or connecting route', max_length=20)),
                ('hub_airport_code', models.CharField(blank=True, help_text='IATA code for the connection hub airport (connecting routes only)', max_length=3, null=True)),
                ('is_promoted', models.BooleanField(default=False, help_text='Whether this route is promoted and visible to users')),
                ('origin_airport_name', models.CharField(help_text='Name of the origin airport', max_length=255)),
                ('destination_airport_name', models.CharField(help_text='Name of the destination airport', max_length=255)),
                ('hub_airport_name', models.CharField(blank=True, help_text='Name of the connection hub airport', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direct_route', models.ForeignKey(blank=True, help_text='Direct route reference', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_connections', to='explore.route')),
                ('first_leg_route', models.ForeignKey(blank=True, help_text='First leg of connecting route', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_leg_connections', to='explore.route')),
                ('second_leg_route', models.ForeignKey(blank=True, help_text='Second leg of connecting route', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_leg_connections', to='explore.route')),
            ],
            options={
                'verbose_name': 'Route Connection',
                'verbose_name_plural': 'Route Connections',
                'ordering': ['origin_airport_code', 'route_type', 'destination_airport_code'],
                'indexes': [models.Index(fields=['origin_airport_code'], name='explore_con_origin__a4ff1d_idx'), models.Index(fields=['destination_airport_code'], name='explore_con_destina_cdc565_idx'), models.Index(fields=['route_type'], name='explore_con_route_t_f437da_idx'), models.Index(fields=['hub_airport_code'], name='explore_con_hub_air_3a514c_idx'), models.Index(fields=['is_promoted'], name='explore_con_is_prom_681a5f_idx')],
                'unique_together': {('origin_airport_code', 'destination_airport_code', 'route_type', 'hub_airport_code')},
            },
        ),
    ]
