# Generated by Django 5.2 on 2025-08-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0060_connectingroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_port', models.CharField(help_text='IATA code for origin port', max_length=3)),
                ('destination_port', models.CharField(help_text='IATA code for destination port', max_length=3)),
            ],
            options={
                'verbose_name': 'Port Pair',
                'verbose_name_plural': 'Port Pairs',
                'indexes': [models.Index(fields=['origin_port'], name='explore_por_origin__ef5a42_idx')],
                'unique_together': {('origin_port', 'destination_port')},
            },
        ),
        migrations.DeleteModel(
            name='ConnectingRoute',
        ),
    ]
