# Generated by Django 5.2 on 2025-08-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0061_portpair_delete_connectingroute'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='portpair',
            name='explore_por_origin__ef5a42_idx',
        ),
        migrations.RenameField(
            model_name='portpair',
            old_name='destination_port',
            new_name='destination_port_code',
        ),
        migrations.RenameField(
            model_name='portpair',
            old_name='origin_port',
            new_name='origin_port_code',
        ),
        migrations.AlterUniqueTogether(
            name='portpair',
            unique_together={('origin_port_code', 'destination_port_code')},
        ),
        migrations.AddIndex(
            model_name='portpair',
            index=models.Index(fields=['origin_port_code'], name='explore_por_origin__b34348_idx'),
        ),
    ]
