# Generated by Django 5.2 on 2025-08-07 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_airport_portpair"),
        ("explore", "0062_remove_portpair_explore_por_origin__ef5a42_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PortPair",
        ),
        migrations.AddField(
            model_name="route",
            name="destination_port",
            field=models.ForeignKey(
                help_text="Destination port for the route",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="destination_routes",
                to="core.airport",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="origin_port",
            field=models.ForeignKey(
                help_text="Origin port for the route",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="origin_routes",
                to="core.airport",
            ),
        ),
        migrations.RemoveField(
            model_name="route",
            name="arrival_airport",
        ),
        migrations.RemoveField(
            model_name="route",
            name="arrival_airport_code",
        ),
        migrations.RemoveField(
            model_name="route",
            name="departure_airport",
        ),
        migrations.RemoveField(
            model_name="route",
            name="departure_airport_code",
        ),
    ]
