# Generated by Django 5.2 on 2025-06-17 02:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutindexpage_hero_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutindexpage',
            name='call_to_action_image',
            field=models.ForeignKey(blank=True, help_text='Background image for the call to action section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aboutindexpage',
            name='journey',
            field=wagtail.fields.StreamField([('journey_item', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('core.blocks.TextBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Year of the journey item', 'max_length': 4, 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('year', 2)]], {})}, help_text='Add items to the Solomon Airlines journey timeline.', verbose_name='Journey Timeline'),
        ),
        migrations.AddField(
            model_name='aboutindexpage',
            name='mission_statement',
            field=wagtail.fields.RichTextField(blank=True, help_text='Solomon Airlines mission statement'),
        ),
        migrations.AddField(
            model_name='aboutindexpage',
            name='values',
            field=wagtail.fields.StreamField([('value_item', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('core.blocks.TextBlock', (), {'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {})}, help_text='Values of Solomon Airlines', verbose_name='Values'),
        ),
        migrations.AddField(
            model_name='aboutindexpage',
            name='vision_statement',
            field=wagtail.fields.RichTextField(blank=True, help_text='Solomon Airlines vision statement'),
        ),
    ]
