# Generated by Django 5.2 on 2025-06-17 02:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_aboutindexpage_call_to_action_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutindexpage',
            name='stats',
            field=wagtail.fields.StreamField([('stat_item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('value', 1)]], {})}, help_text='Some cool stats related to Solomon Airlines', verbose_name='Statistics'),
        ),
    ]
