# Generated by Django 5.2 on 2025-06-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_aboutindexpage_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutindexpage',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=2000),
        ),
    ]
