# Generated by Django 5.2 on 2025-08-13 02:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_alter_aboutindexpage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutindexpage',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Hero video for the about page', null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='aboutindexpage',
            name='magazines',
            field=wagtail.fields.StreamField([('magazine', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Magazine title', 'max_length': 100, 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Cover image for the magazine', 'required': True}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Magazine document (PDF, etc.)', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('cover_image', 1), ('document', 2)]], {})}, help_text='Add magazines with documents, cover images and titles.', verbose_name='Magazines'),
        ),
        migrations.AddField(
            model_name='aboutindexpage',
            name='stories',
            field=wagtail.fields.StreamField([('story', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Story title', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Story subtitle', 'max_length': 200, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Cover image for the story', 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL link to the full story', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('cover_image', 2), ('url', 3)]], {})}, help_text='Add stories with cover images, titles, subtitles and URLs.', verbose_name='Stories'),
        ),
    ]
