# Generated by Django 5.2 on 2025-08-18 00:19

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_aboutindexpage_hero_video_aboutindexpage_magazines_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Page title or tagline for hero section', max_length=255)),
                ('sub_title', models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='A description of the page.')),
                ('hero_video', models.FileField(blank=True, help_text='Hero video for the careers page', null=True, upload_to='videos/')),
                ('life_value_points', wagtail.fields.StreamField([('life_value_point', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image for the value point', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Value point title', 'max_length': 100, 'required': True}), 2: ('core.blocks.TextBlock', (), {'help_text': 'Value point description', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2)]], {})}, help_text='Life at company value points with image, title and description', verbose_name='Life at Solomon Airlines Highlights Points')),
                ('departments', wagtail.fields.StreamField([('department', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Department name', 'max_length': 100, 'required': True}), 1: ('core.blocks.TextBlock', (), {'help_text': 'Department description', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Department image', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('department_name', 0), ('description', 1), ('image', 2)]], {})}, help_text='Departments with name, description and image', verbose_name='Departments')),
                ('benefits', wagtail.fields.StreamField([('benefit', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Benefit title', 'max_length': 100, 'required': True}), 1: ('core.blocks.TextBlock', (), {'help_text': 'Benefit description', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})}, help_text='Benefits with title and description', verbose_name='Benefits')),
                ('hero_image', models.ForeignKey(blank=True, help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('svg_icon', models.ForeignKey(blank=True, help_text='SVG icon for the page, used in other sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Careers Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
