# Generated by Django 5.2 on 2025-08-18 00:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_remove_careerspage_life_value_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerspage',
            name='culture_highlights',
            field=wagtail.fields.StreamField([('culture_highlight', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image for the culture highlight', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Culture highlight title', 'max_length': 100, 'required': True}), 2: ('core.blocks.TextBlock', (), {'help_text': 'Culture highlight description', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2)]], {})}, help_text='Company culture highlights with image, title and description (maximum 3)', verbose_name='Company Culture Highlights'),
        ),
    ]
