# Generated by Django 5.2 on 2025-08-18 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_alter_careerspage_culture_highlights'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(help_text='Job position title', max_length=200)),
                ('department_name', models.CharField(help_text='Department name', max_length=100)),
                ('location', models.CharField(help_text='Job location', max_length=100)),
                ('closing_date', models.DateField(help_text='Application closing date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, help_text='Job vacancy document (PDF)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'verbose_name': 'Job Vacancy',
                'verbose_name_plural': 'Job Vacancies',
                'ordering': ['-created_at'],
            },
        ),
    ]
