# Generated by Django 5.2 on 2025-08-28 04:42

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_jobvacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutindexpage',
            name='history_body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Content for the history section'),
        ),
        migrations.AddField(
            model_name='aboutindexpage',
            name='history_title',
            field=models.CharField(blank=True, help_text='Title for the history section', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutindexpage',
            name='present_body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Content for the present section'),
        ),
        migrations.AddField(
            model_name='aboutindexpage',
            name='present_title',
            field=models.CharField(blank=True, help_text='Title for the present section', max_length=200),
        ),
    ]
