# Generated by Django 5.2 on 2025-05-19 03:12

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BelamaIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Page title or tagline for hero section', max_length=255)),
                ('description', models.CharField(blank=True, help_text='A short description of the page.', max_length=255)),
                ('individual_memberships', wagtail.fields.StreamField([('individual_membership', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'features': ['ol', 'ul'], 'help_text': 'A list of features for the membership', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('price', 0), ('features', 1)]], {})}, help_text='Add individual memberships.')),
                ('group_memberships', wagtail.fields.StreamField([('group_membership', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'features': ['ol', 'ul'], 'help_text': 'A list of features for the membership', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('price', 0), ('features', 1)]], {})}, help_text='Add group memberships.')),
                ('hero_image', models.ForeignKey(blank=True, help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('promo_image', models.ForeignKey(blank=True, help_text='A promotional image for Belama', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Belama Index Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
