# Generated by Django 5.2 on 2025-05-19 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belama', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BelamaSignUpPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Page title or tagline for hero section', max_length=255)),
                ('description', models.CharField(blank=True, help_text='A short description of the page.', max_length=255)),
                ('hero_image', models.ForeignKey(blank=True, help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Belama Sign Up Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
