# Generated by Django 5.2 on 2025-06-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belama', '0003_alter_belamaindexpage_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belamaindexpage',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='belamasignuppage',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=2000),
        ),
    ]
