# Generated by Django 5.2 on 2025-06-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belama', '0004_alter_belamaindexpage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='belamaindexpage',
            name='sub_title',
            field=models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='belamasignuppage',
            name='sub_title',
            field=models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100),
        ),
    ]
