# Generated by Django 5.2 on 2025-06-25 10:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belama', '0005_belamaindexpage_sub_title_belamasignuppage_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belamaindexpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short description of the page.'),
        ),
        migrations.AlterField(
            model_name='belamasignuppage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short description of the page.'),
        ),
    ]
