# Generated by Django 5.2 on 2025-06-30 21:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belama', '0006_alter_belamaindexpage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belamaindexpage',
            name='group_memberships',
            field=wagtail.fields.StreamField([('group_membership', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Check this box if this is the most popular membership', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'features': ['ol', 'ul'], 'help_text': 'A list of features for the membership', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('price', 0), ('most_popular', 1), ('features', 2)]], {})}, help_text='Add group memberships.'),
        ),
        migrations.AlterField(
            model_name='belamaindexpage',
            name='individual_memberships',
            field=wagtail.fields.StreamField([('individual_membership', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Check this box if this is the most popular membership', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'features': ['ol', 'ul'], 'help_text': 'A list of features for the membership', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('price', 0), ('most_popular', 1), ('features', 2)]], {})}, help_text='Add individual memberships.'),
        ),
    ]
