# Generated by Django 5.2 on 2025-07-01 10:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belama', '0011_alter_belamaindexpage_svg_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belamaindexpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A description of the page.'),
        ),
        migrations.AlterField(
            model_name='belamasignuppage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A description of the page.'),
        ),
    ]
