# Generated by Django 5.2 on 2025-08-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belama', '0013_alter_belamaindexpage_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='belamasignuppage',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address for Belama sign up', max_length=254, verbose_name='Email'),
        ),
    ]
