# Generated by Django 5.2 on 2025-07-28 00:12

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Page title or tagline for hero section', max_length=255)),
                ('sub_title', models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='A description of the page.')),
                ('contact_sections', wagtail.fields.StreamField([('contact_category', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Category name (e.g., 'Reservations', 'Cargo')", 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Brief description of this contact category', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('phone', 'Phone'), ('email', 'Email'), ('fax', 'Fax'), ('address', 'Physical Address'), ('hours', 'Operating Hours')], 'help_text': 'Type of contact method'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Display label (e.g., 'Main Office', 'After Hours')", 'max_length': 100, 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Contact details (phone number, email, address, etc.)', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('method_type', 2), ('contact_label', 3), ('contact_value', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Direct contact methods for this category', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': "Subcategory name (e.g., 'New Bookings', 'Corporate Travel')", 'max_length': 100, 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Brief description of this subcategory', 'required': False}), 9: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Contact methods for this subcategory'}), 10: ('wagtail.blocks.StructBlock', [[('subcategory_name', 7), ('subcategory_description', 8), ('contact_methods', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'help_text': 'Subcategories with their own contact methods', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('category_name', 0), ('category_description', 1), ('contact_methods', 6), ('subcategories', 11)]], {})}, help_text='Add contact categories with their methods and subcategories', verbose_name='Contact Sections')),
                ('hero_image', models.ForeignKey(help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('svg_icon', models.ForeignKey(blank=True, help_text='SVG icon for the page, used in other sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
