# Generated by Django 5.2 on 2025-07-28 00:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='contact_sections',
            field=wagtail.fields.StreamField([('contact_category', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Category name (e.g., 'Reservations', 'Cargo')", 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Brief description of this contact category', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('phone', 'Phone'), ('email', 'Email'), ('fax', 'Fax'), ('address', 'Physical Address')], 'help_text': 'Type of contact method'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Display label (e.g., 'Main Office', 'After Hours')", 'max_length': 100, 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Contact details (phone number, email, address, etc.)', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional subcategory name (e.g., 'New Bookings'). Leave blank for direct contact methods.", 'max_length': 100, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('method_type', 2), ('contact_label', 3), ('contact_value', 4), ('subcategory_name', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'Contact methods for this category. Use subcategory name to group methods.'}), 8: ('wagtail.blocks.StructBlock', [[('category_name', 0), ('category_description', 1), ('contact_methods', 7)]], {})}, help_text='Add contact categories with their methods and subcategories', verbose_name='Contact Sections'),
        ),
    ]
