# Generated by Django 5.2 on 2025-07-28 00:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactpage_contact_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='contact_sections',
            field=wagtail.fields.StreamField([('contact_category', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Category name', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Brief description of this contact category', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('phone', 'Phone'), ('email', 'Email'), ('fax', 'Fax'), ('address', 'Physical Address')], 'help_text': 'Type of contact method'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Contact details (phone number, email, address, etc.)', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('method_type', 2), ('contact_value', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'help_text': 'Direct contact methods for this category (no subcategory)', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subcategory name', 'max_length': 100, 'required': True}), 7: ('wagtail.blocks.ListBlock', (4,), {'help_text': 'Contact methods for this subcategory'}), 8: ('wagtail.blocks.StructBlock', [[('subcategory_name', 6), ('contact_methods', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'help_text': 'Subcategories with their own contact methods', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('category_name', 0), ('category_description', 1), ('direct_contact_methods', 5), ('subcategories', 9)]], {})}, help_text='Add contact categories with their methods and subcategories', verbose_name='Contact Sections'),
        ),
    ]
