# Generated by Django 5.2 on 2025-07-28 04:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contactpage_contact_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='contact_sections',
            field=wagtail.fields.StreamField([('contact_category', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Category name', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Brief description of this contact category', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subcategory name', 'max_length': 100, 'required': True}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('phone', 'Phone'), ('email', 'Email'), ('fax', 'Fax'), ('address', 'Physical Address'), ('website', 'Website URL'), ('hours', 'Opening Hours'), ('closing', 'Closing Times'), ('note', 'Additional Note')], 'help_text': 'Type of contact method'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Contact details (phone number, email, address, etc.)', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('method_type', 3), ('contact_value', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Contact methods for this subcategory'}), 7: ('wagtail.blocks.StructBlock', [[('subcategory_name', 2), ('contact_methods', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'Subcategories with their own contact methods'}), 9: ('wagtail.blocks.StructBlock', [[('category_name', 0), ('category_description', 1), ('subcategories', 8)]], {})}, help_text='Add contact categories with their methods and subcategories', verbose_name='Contact Sections'),
        ),
    ]
