# Generated by Django 5.2 on 2025-08-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_contactpage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254, verbose_name='Email'),
        ),
    ]
