# Generated by Django 5.2 on 2025-08-13 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_contactpage_email'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='call_to_action_image',
            field=models.ForeignKey(blank=True, help_text='Background image for the call to action section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='call_to_action_subtitle',
            field=models.CharField(blank=True, help_text='Subtitle for the call to action section', max_length=200, verbose_name='Call to Action Subtitle'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='call_to_action_title',
            field=models.CharField(blank=True, help_text='Title for the call to action section', max_length=100, verbose_name='Call to Action Title'),
        ),
    ]
