# Generated by Django 5.2 on 2025-04-28 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('start_date', 'end_date')},
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('flight_number', models.CharField(max_length=10)),
                ('departure_port', models.CharField(max_length=50)),
                ('arrival_port', models.CharField(max_length=50)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('flight_scope', models.CharField(max_length=50)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='schedules.schedule')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
            },
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='arrival_port',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='departure_port',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='flight_scope',
        ),
    ]
