# Generated by Django 5.2 on 2025-04-30 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_port',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Time must be in HHMM format (e.g., 1100).')]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_port',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Time must be in HHMM format (e.g., 0800).')]),
        ),
    ]
