# Generated by Django 5.2 on 2025-07-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_flight_arrival_port_alter_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.CharField(default='X', max_length=30),
            preserve_default=False,
        ),
    ]
