# Generated by Django 5.2 on 2025-04-09 02:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='tagline',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
