# Generated by Django 5.2 on 2025-04-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='tagline',
            field=models.CharField(blank=True, help_text='A short tagline for the homepage', max_length=255),
        ),
    ]
