# Generated by Django 5.2 on 2025-04-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_tagline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='featured_image',
            new_name='hero_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='tagline',
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_title',
            field=models.CharField(blank=True, help_text='Page title or tagline for hero section', max_length=255),
        ),
    ]
