# Generated by Django 5.2 on 2025-04-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_featured_image_homepage_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='page_title',
            field=models.CharField(help_text='Page title or tagline for hero section', max_length=255),
        ),
    ]
