# Generated by Django 5.2 on 2025-04-09 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_page_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='page_title',
            new_name='hero_title',
        ),
    ]
