# Generated by Django 5.2 on 2025-06-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=255),
        ),
    ]
