# Generated by Django 5.2 on 2025-06-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homepage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sub_title',
            field=models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100),
        ),
    ]
