# Generated by Django 5.2 on 2025-07-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0047_alter_special_booking_class_alter_special_name_and_more'),
        ('home', '0014_alter_homepage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='special_routes',
            field=models.ManyToManyField(blank=True, help_text='Special routes to display on the homepage', related_name='homepages', to='explore.specialroute'),
        ),
    ]
