# Generated by Django 5.2 on 2025-07-01 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepage_special_routes'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='all_you_need_pages',
            field=models.ManyToManyField(blank=True, help_text='Select up to 6 pages for the All You Need section', related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='belama_image',
            field=models.ForeignKey(blank=True, help_text='Image for the Belama section on the homepage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
