# Generated by Django 5.2 on 2025-07-01 04:34

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_homepage_all_you_need_pages_homepage_belama_image'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='all_you_need_pages',
        ),
        migrations.CreateModel(
            name='AllYouNeedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_you_need_items', to='home.homepage')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'unique_together': {('homepage', 'page')},
            },
        ),
    ]
