# Generated by Django 5.2 on 2025-07-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_homepage_all_you_need_pages_allyouneedpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allyouneedpage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
