# Generated by Django 5.2 on 2025-07-01 05:04

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0047_alter_special_booking_class_alter_special_name_and_more'),
        ('home', '0018_alter_allyouneedpage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='special_routes',
        ),
        migrations.CreateModel(
            name='HomePageSpecialRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_route_items', to='home.homepage')),
                ('special_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_specials', to='explore.specialroute')),
            ],
            options={
                'unique_together': {('homepage', 'special_route')},
            },
        ),
    ]
