# Generated by Django 5.2 on 2025-07-01 10:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_homepage_svg_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A description of the page.'),
        ),
    ]
