# Generated by Django 5.2 on 2025-07-04 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0053_alter_destination_travel_requirements'),
        ('home', '0023_alter_homepage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagespecialroute',
            name='special_route',
            field=models.ForeignKey(limit_choices_to={'is_expired': False}, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_specials', to='explore.specialroute'),
        ),
    ]
