# Generated by Django 5.2 on 2025-07-04 02:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0053_alter_destination_travel_requirements'),
        ('home', '0024_alter_homepagespecialroute_special_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagespecialroute',
            name='special_route',
            field=models.ForeignKey(limit_choices_to={'special__end_date__gte': datetime.date(2025, 7, 4)}, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_specials', to='explore.specialroute'),
        ),
    ]
