# Generated by Django 5.2 on 2025-07-21 08:44

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_homepagespecialroute_special_route'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the carousel slide', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle for the carousel slide', max_length=255)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Optional description for the carousel slide')),
                ('video_url', models.URLField(blank=True, help_text='Optional video URL (takes precedence over image if provided)')),
                ('call_to_action_text', models.CharField(blank=True, help_text='Button text for call to action', max_length=50)),
                ('call_to_action_url', models.URLField(blank=True, help_text='URL for the call to action button')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slide is active and should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, help_text='Background image for the carousel slide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'verbose_name_plural': 'Carousel Slides',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePageCarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which the slide appears in the carousel (lower numbers appear first)')),
                ('homepage', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_slides', to='home.homepage')),
                ('slide', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_associations', to='home.carouselslide')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('homepage', 'slide')},
            },
        ),
    ]
