# Generated by Django 5.2 on 2025-07-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_carouselslide_homepagecarouselslide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselslide',
            name='call_to_action_text',
        ),
        migrations.RemoveField(
            model_name='carouselslide',
            name='call_to_action_url',
        ),
        migrations.RemoveField(
            model_name='carouselslide',
            name='description',
        ),
        migrations.RemoveField(
            model_name='carouselslide',
            name='subtitle',
        ),
    ]
