# Generated by Django 5.2 on 2025-07-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_carouselslide_call_to_action_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselslide',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='carouselslide',
            name='video_url',
        ),
    ]
