# Generated by Django 5.2 on 2025-07-21 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_carouselslide_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='svg_icon',
        ),
        migrations.AlterField(
            model_name='homepagecarouselslide',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_associations', to='home.carouselslide'),
        ),
    ]
