# Generated by Django 5.2 on 2025-07-21 21:41

import datetime
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0059_routerelatedroute'),
        ('home', '0034_remove_homepage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselslide',
            name='subheading',
            field=wagtail.fields.RichTextField(blank=True, help_text='Subheading for the carousel slide (can include links)', null=True),
        ),
        migrations.AlterField(
            model_name='homepagespecialroute',
            name='special_route',
            field=models.ForeignKey(limit_choices_to={'special__end_date__gte': datetime.date(2025, 7, 22)}, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_specials', to='explore.specialroute'),
        ),
    ]
