# Generated by Django 5.2 on 2025-07-22 22:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0059_routerelatedroute'),
        ('home', '0035_carouselslide_subheading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagespecialroute',
            name='special_route',
            field=models.ForeignKey(limit_choices_to={'special__end_date__gte': datetime.date(2025, 7, 23)}, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_specials', to='explore.specialroute'),
        ),
    ]
