# Generated by Django 5.2 on 2025-07-31 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0059_routerelatedroute'),
        ('home', '0042_alter_homepagespecialroute_special_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagespecialroute',
            name='special_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_specials', to='explore.specialroute'),
        ),
    ]
