# Generated by Django 5.2 on 2025-04-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_family', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('trip_type', models.CharField(default='one way', max_length=10)),
                ('origin', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('route', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Fare',
                'verbose_name_plural': 'Fares',
            },
        ),
    ]
