# Generated by Django 5.2 on 2025-04-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare',
            name='trip_type',
            field=models.CharField(default='One Way', max_length=10),
        ),
    ]
