# Generated by Django 5.2 on 2025-05-14 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0002_alter_fare_trip_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fare',
            name='route',
        ),
    ]
