# Generated by Django 5.2 on 2025-05-14 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0022_alter_route_name_alter_route_unique_together'),
        ('fares', '0003_remove_fare_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='fare',
            name='route',
            field=models.ForeignKey(blank=True, help_text='The route this fare applies to (e.g., JFK-LAX)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fares', to='explore.route'),
        ),
    ]
