# Generated by Django 5.2 on 2025-05-14 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0022_alter_route_name_alter_route_unique_together'),
        ('fares', '0004_fare_route'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fare',
            unique_together={('fare_family', 'route')},
        ),
    ]
