# Generated by Django 5.2 on 2025-04-10 03:03

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='intro',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='article_title',
            field=models.CharField(blank=True, help_text='Article title', max_length=255),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
