# Generated by Django 5.2 on 2025-04-15 22:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_newsarticle_intro_newsarticle_article_title_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='article_title',
            field=models.CharField(help_text='The title of the news article', max_length=255),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='body',
            field=wagtail.fields.RichTextField(help_text='The content of the article'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='date',
            field=models.DateField(help_text='The date of the news article'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='newsindexpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
