# Generated by Django 5.2 on 2025-04-15 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsarticle_article_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='date',
        ),
    ]
