# Generated by Django 5.2 on 2025-04-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_newsarticle_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'verbose_name': 'News Article', 'verbose_name_plural': 'News Articles'},
        ),
        migrations.AlterModelOptions(
            name='newsindexpage',
            options={'verbose_name': 'News Index Page'},
        ),
    ]
