# Generated by Django 5.2 on 2025-06-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsarticle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=255),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=255),
        ),
    ]
