# Generated by Django 5.2 on 2025-06-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_newsarticle_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='sub_title',
            field=models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='sub_title',
            field=models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100),
        ),
    ]
