# Generated by Django 5.2 on 2025-06-25 10:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_newsarticle_sub_title_newsindexpage_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short description of the page.'),
        ),
        migrations.AlterField(
            model_name='newsindexpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short description of the page.'),
        ),
    ]
