# Generated by Django 5.2 on 2025-07-01 10:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_newsarticle_svg_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A description of the page.'),
        ),
        migrations.AlterField(
            model_name='newsindexpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A description of the page.'),
        ),
    ]
