# Generated by Django 5.2 on 2025-07-26 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_newsarticle_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this category covers')),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a category for this news article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.newscategory'),
        ),
    ]
