# Generated by Django 5.2 on 2025-07-27 04:36

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_newscategory_newsarticle_category'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Page title or tagline for hero section', max_length=255)),
                ('sub_title', models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='A description of the page.')),
                ('category_description', models.TextField(blank=True, help_text='Brief description of what this category covers')),
                ('hero_image', models.ForeignKey(help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('legacy_category', models.OneToOneField(blank=True, help_text='Linked legacy category (for migration only)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newscategory')),
                ('svg_icon', models.ForeignKey(blank=True, help_text='SVG icon for the page, used in other sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'News Category Page',
                'verbose_name_plural': 'News Category Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
