# Generated by Django 5.2 on 2025-07-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_newscategorypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategorypage',
            name='legacy_category',
        ),
    ]
