# Generated by Django 5.2 on 2025-07-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_remove_newscategorypage_legacy_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='category',
        ),
        migrations.AddField(
            model_name='newscategorypage',
            name='category_name',
            field=models.CharField(blank=True, help_text='Display name for this category (if different from page title)', max_length=100),
        ),
    ]
