# Generated by Django 5.2 on 2025-08-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_remove_newsarticle_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsCategory',
        ),
    ]
