# Generated by Django 5.2 on 2025-04-24 22:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienceindexpage',
            options={'verbose_name': 'Experience Index Page'},
        ),
        migrations.AddField(
            model_name='experienceindexpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short description of the page'),
        ),
    ]
