# Generated by Django 5.2 on 2025-06-25 10:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_experienceindexpage_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceindexpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short description of the page.'),
        ),
    ]
