# Generated by Django 5.2 on 2025-07-01 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0007_alter_experienceindexpage_description'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceindexpage',
            name='svg_icon',
            field=models.ForeignKey(blank=True, help_text='SVG icon for the page, used in other sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
