# Generated by Django 5.2 on 2025-07-01 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_svgimage_alter_genericpage_svg_icon_svgrendition'),
        ('experience', '0008_experienceindexpage_svg_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceindexpage',
            name='svg_icon',
            field=models.ForeignKey(blank=True, help_text='SVG icon for the page, used in other sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.svgimage'),
        ),
    ]
