# Generated by Django 5.2 on 2025-04-22 00:59

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Page title or tagline for hero section', max_length=255)),
                ('content', wagtail.fields.StreamField([('text', 0), ('image', 4), ('section', 9), ('grid_card', 16), ('heading_text', 19)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Add a paragraph with rich text formatting (e.g., bold, links).'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Select an image.', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional image caption.', 'max_length': 200, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alt text for accessibility.', 'max_length': 125, 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alt_text', 3)]], {'help_text': 'Add an image with optional caption.'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading.', 'max_length': 100, 'required': True}), 6: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Section body text with rich formatting.', 'required': True}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image to display on the right.', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alt text for image.', 'max_length': 125, 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('heading', 5), ('text', 6), ('image', 7), ('alt_text', 8)]], {'help_text': 'Add a section with image on right and heading/text on left.'}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card heading.', 'max_length': 100, 'required': True}), 11: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Card body text.', 'required': True}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Card image.', 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alt text for card image.', 'max_length': 125, 'required': True}), 14: ('wagtail.blocks.StructBlock', [[('heading', 10), ('text', 11), ('image', 12), ('alt_text', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'help_text': 'Add multiple cards, each with an image, heading, and text.'}), 16: ('wagtail.blocks.StructBlock', [[('cards', 15)]], {'help_text': 'Add a grid of cards (e.g., for features, testimonials).'}), 17: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Body text with rich formatting.', 'required': True}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3')], 'help_text': 'Choose heading level (H2 or H3).', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('heading', 5), ('text', 17), ('heading_level', 18)]], {'help_text': 'Add a simple section with a heading and text only.'})}, help_text='Add and arrange content blocks to build the page.')),
                ('hero_image', models.ForeignKey(blank=True, help_text="Image that will be displayed on this page's hero section", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Generic Page',
                'verbose_name_plural': 'Generic Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
