# Generated by Django 5.2 on 2025-04-22 05:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_genericpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='content',
            field=wagtail.fields.StreamField([('text', 0), ('image', 3), ('section', 8), ('grid_card_section', 15), ('heading_text', 17)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Add a paragraph with rich text formatting (e.g., bold, links).'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Select an image.', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional image caption.', 'max_length': 200, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {'help_text': 'Add an image with optional caption.'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading.', 'max_length': 100, 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Section body text with rich formatting.', 'required': True}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image to display on the right.', 'required': True}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')], 'help_text': 'Choose image position (left or right).', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('heading', 4), ('text', 5), ('image', 6), ('image_position', 7)]], {'help_text': 'Add a section with image on one side and heading/text on the other side.'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Grid section heading.', 'max_length': 100, 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card heading.', 'max_length': 100, 'required': True}), 11: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Card body text.', 'required': True}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Card image.', 'required': True}), 13: ('wagtail.blocks.StructBlock', [[('heading', 10), ('text', 11), ('image', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'help_text': 'Add multiple cards, each with an image, heading, and text.'}), 15: ('wagtail.blocks.StructBlock', [[('heading', 9), ('grid_cards', 14)]], {'help_text': 'Add a grid of cards.'}), 16: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Body text with rich formatting.', 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('heading', 4), ('text', 16)]], {'help_text': 'Add a simple section with a heading and text only.'})}, help_text='Add and arrange content blocks to build the page.'),
        ),
    ]
