# Generated by Django 5.2 on 2025-04-23 00:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_genericpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='content',
            field=wagtail.fields.StreamField([('text', 0), ('image', 3), ('section', 7), ('grid_card_section', 10), ('heading_text', 11)], blank=True, block_lookup={0: ('core.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 5: ('core.blocks.TextBlock', (), {'required': True}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 7: ('wagtail.blocks.StructBlock', [[('heading', 4), ('text', 5), ('image', 1), ('image_position', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('heading', 4), ('text', 5), ('image', 1)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('heading', 4), ('grid_cards', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 4), ('text', 5)]], {})}, help_text='Add and arrange content blocks to build the page.'),
        ),
    ]
