# Generated by Django 5.2 on 2025-06-10 02:32

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_genericpage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the menu (e.g., Main Menu)', max_length=100)),
                ('menu_items', wagtail.fields.StreamField([('mega_menu_item', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a page to link to.', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter an external URL to link to.', 'max_length': 200, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Column title', 'max_length': 100, 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 4), ('link_page', 5), ('external_url', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'Menu items in this column'}), 9: ('wagtail.blocks.StructBlock', [[('column_title', 3), ('items', 8)]], {'help_text': 'Mega menu columns'}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 0), ('link_page', 1), ('external_link', 2), ('columns', 10)]], {})})),
            ],
            options={
                'verbose_name': 'Header Menu',
                'verbose_name_plural': 'Header Menus',
            },
        ),
    ]
