# Generated by Django 5.2 on 2025-06-10 22:08

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_headermenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the footer menu (e.g., Footer Menu)', max_length=100)),
                ('menu_items', wagtail.fields.StreamField([('mega_menu_item', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Column title', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Item title', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a page to link to.', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter an external URL to link to.', 'max_length': 200, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 1), ('link_page', 2), ('external_url', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('column_title', 0), ('items', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {})})),
            ],
            options={
                'verbose_name': 'Footer Menu',
                'verbose_name_plural': 'Footer Menus',
            },
        ),
        migrations.AlterModelOptions(
            name='headermenu',
            options={'verbose_name': 'Header Menu', 'verbose_name_plural': 'Header Menu'},
        ),
        migrations.AlterField(
            model_name='headermenu',
            name='menu_items',
            field=wagtail.fields.StreamField([('mega_menu_item', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a page to link to.', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter an external URL to link to.', 'max_length': 200, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Column title', 'max_length': 100, 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Item title', 'max_length': 100, 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('title', 4), ('link_page', 1), ('external_url', 2)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('column_title', 3), ('items', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('link_page', 1), ('external_link', 2), ('columns', 8)]], {})}),
        ),
    ]
