# Generated by Django 5.2 on 2025-06-10 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_footermenu_alter_headermenu_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footermenu',
            options={'verbose_name': 'Footer Menu', 'verbose_name_plural': 'Footer Menu'},
        ),
    ]
