# Generated by Django 5.2 on 2025-06-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_footermenu_menu_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of the page.', max_length=255),
        ),
    ]
