# Generated by Django 5.2 on 2025-06-11 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_genericpage_description'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(help_text='Name of the country', max_length=100)),
                ('currency_name', models.CharField(help_text='Name of the currency', max_length=100)),
                ('currency_code', models.CharField(help_text='Currency code (e.g., USD, EUR)', max_length=10)),
                ('currency_symbol', models.CharField(help_text='Symbol for the currency (e.g., $, €)', max_length=10)),
                ('flag_image', models.ForeignKey(blank=True, help_text='Flag icon for the country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
