# Generated by Django 5.2 on 2025-06-18 00:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_genericpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='content',
            field=wagtail.fields.StreamField([('text', 0), ('image', 3), ('section', 8), ('grid_card_section', 11), ('heading_text', 12)], blank=True, block_lookup={0: ('core.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 5: ('core.blocks.TextBlock', (), {'required': True}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 7: ('wagtail_color_panel.blocks.NativeColorBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('heading', 4), ('text', 5), ('image', 1), ('image_position', 6), ('background_color', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('heading', 4), ('text', 5), ('image', 1)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 4), ('grid_cards', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 4), ('text', 5)]], {})}, help_text='Add and arrange content blocks to build the page.'),
        ),
    ]
