# Generated by Django 5.2 on 2025-06-18 00:38

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_genericpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='sub_title',
            field=models.CharField(blank=True, help_text='A short subtitle for the page.', max_length=100),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='content',
            field=wagtail.fields.StreamField([('text', 0), ('image', 4), ('full_width_image', 5), ('section', 9), ('grid_card_section', 12), ('heading_text', 13)], blank=True, block_lookup={0: ('core.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 3: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('background_color', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 7: ('core.blocks.TextBlock', (), {'required': True}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 9: ('wagtail.blocks.StructBlock', [[('heading', 6), ('text', 7), ('image', 1), ('image_position', 8), ('background_color', 3)]], {}), 10: ('wagtail.blocks.StructBlock', [[('heading', 6), ('text', 7), ('image', 1)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 6), ('grid_cards', 11), ('background_color', 3)]], {}), 13: ('wagtail.blocks.StructBlock', [[('heading', 6), ('text', 7)]], {})}, help_text='Add and arrange content blocks to build the page.'),
        ),
    ]
