# Generated by Django 5.2 on 2025-06-25 10:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_genericpage_sub_title_alter_genericpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short description of the page.'),
        ),
    ]
