# Generated by Django 5.2 on 2025-07-01 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_svgimage_alter_genericpage_svg_icon_svgrendition'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svgimage',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='svgimage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='svgimage',
            name='uploaded_by_user',
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='svg_icon',
            field=models.ForeignKey(blank=True, help_text='SVG icon for the page, used in other sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.DeleteModel(
            name='SVGRendition',
        ),
    ]
