# Generated by Django 5.2 on 2025-07-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_alter_aboutindexpage_svg_icon'),
        ('belama', '0011_alter_belamaindexpage_svg_icon_and_more'),
        ('core', '0023_remove_svgimage_collection_remove_svgimage_tags_and_more'),
        ('experience', '0010_alter_experienceindexpage_svg_icon'),
        ('explore', '0050_alter_destination_svg_icon_and_more'),
        ('home', '0022_alter_homepage_svg_icon'),
        ('news', '0013_alter_newsarticle_svg_icon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SVGImage',
        ),
    ]
