# Generated by Django 5.2 on 2025-07-01 10:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_delete_svgimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A description of the page.'),
        ),
    ]
