# Generated by Django 5.2 on 2025-07-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_genericpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country_code',
            field=models.CharField(default='SB', help_text='Country code (e.g., SB, AU, NZ)', max_length=10),
            preserve_default=False,
        ),
    ]
