# Generated by Django manually to remove wagtail_color_panel references

from django.db import migrations
import wagtail.fields
import core.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_genericpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='content',
            field=wagtail.fields.StreamField([
                ('text', core.blocks.TextBlock()),
                ('image', core.blocks.ImageBlock()),
                ('full_width_image', core.blocks.FullWidthImageBlock()),
                ('section', core.blocks.SectionBlock()),
                ('grid_card_section', core.blocks.GridCardSectionBlock()),
                ('heading_text', core.blocks.HeadingTextBlock())
            ], blank=True, help_text='Add and arrange content blocks to build the page.'),
        ),
    ]