# Generated by Django 5.2 on 2025-07-21 04:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_genericpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='content',
            field=wagtail.fields.StreamField([('text', 0), ('image', 3), ('full_width_image', 3), ('section', 7), ('grid_card_section', 11), ('heading_text', 12), ('table', 14), ('accordion', 23)], blank=True, block_lookup={0: ('core.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 5: ('core.blocks.TextBlock', (), {'required': True}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 7: ('wagtail.blocks.StructBlock', [[('heading', 4), ('text', 5), ('image', 1), ('image_position', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'features': ['link'], 'help_text': 'A link that this card will point to.', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('heading', 4), ('text', 5), ('image', 1), ('url', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 4), ('grid_cards', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 4), ('text', 5)]], {}), 13: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'colHeaders': False, 'rowHeaders': False, 'startCols': 3, 'startRows': 3}}), 14: ('wagtail.blocks.StructBlock', [[('table_data', 13)]], {}), 15: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a page to link to.', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Column title', 'max_length': 100, 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Item title', 'max_length': 100, 'required': True}), 18: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a page to link to.', 'required': True}), 19: ('wagtail.blocks.StructBlock', [[('title', 17), ('link_page', 18)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {}), 21: ('wagtail.blocks.StructBlock', [[('column_title', 16), ('items', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {}), 23: ('wagtail.blocks.StructBlock', [[('title', 4), ('link_page', 15), ('columns', 22)]], {})}, help_text='Add and arrange content blocks to build the page.'),
        ),
    ]
