# Generated by Django 5.2 on 2025-07-24 02:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_genericpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footermenu',
            name='menu_items',
            field=wagtail.fields.StreamField([('mega_menu_item', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Column title', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Item title', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a page to link to.', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('link_page', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'help_text': 'Maximum 6 items per column', 'max_num': 6}), 5: ('wagtail.blocks.StructBlock', [[('column_title', 0), ('items', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {})}),
        ),
        migrations.AlterField(
            model_name='headermenu',
            name='menu_items',
            field=wagtail.fields.StreamField([('mega_menu_item', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a page to link to.', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Column title', 'max_length': 100, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Item title', 'max_length': 100, 'required': True}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a page to link to.', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('title', 3), ('link_page', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Maximum 6 items per column', 'max_num': 6}), 7: ('wagtail.blocks.StructBlock', [[('column_title', 2), ('items', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('link_page', 1), ('columns', 8)]], {})}),
        ),
    ]
