# Generated by Django 5.2 on 2025-07-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_footermenu_menu_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='include_flight_upgrade_widget',
            field=models.BooleanField(default=False, help_text="Include the 'Flight Upgrade' widget on this page. Only one widget type can be active at a time."),
        ),
        migrations.AddField(
            model_name='genericpage',
            name='include_manage_booking_widget',
            field=models.BooleanField(default=False, help_text="Include the 'Manage My Booking' widget on this page. Only one widget type can be active at a time."),
        ),
    ]
