# Generated by Django 5.2 on 2025-07-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_genericpage_include_flight_upgrade_widget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='include_flight_upgrade_widget',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='include_manage_booking_widget',
            field=models.BooleanField(default=False),
        ),
    ]
