# Generated by Django 5.2 on 2025-08-07 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_genericpage_include_flight_upgrade_widget_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Airport code (e.g., HIR, SYD, LAX)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full airport name (e.g., Honiara International Airport)', max_length=200)),
                ('city', models.CharField(help_text='City where the airport is located', max_length=100)),
                ('country', models.CharField(help_text='Country where the airport is located', max_length=100)),
                ('destination_image', models.ForeignKey(blank=True, help_text='Image representing the destination/airport', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PortPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_port', models.ForeignKey(help_text='Destination airport for this port pair', on_delete=django.db.models.deletion.CASCADE, related_name='destination_port_pairs', to='core.airport')),
                ('origin_port', models.ForeignKey(help_text='Origin airport for this port pair', on_delete=django.db.models.deletion.CASCADE, related_name='origin_port_pairs', to='core.airport')),
            ],
            options={
                'verbose_name': 'Port Pair',
                'verbose_name_plural': 'Port Pairs',
                'indexes': [models.Index(fields=['origin_port'], name='core_portpa_origin__318311_idx')],
                'unique_together': {('origin_port', 'destination_port')},
            },
        ),
    ]
