# Generated by Django 5.2 on 2025-08-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_genericpage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footermenu',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address for the footer', max_length=254, verbose_name='Email'),
        ),
    ]
