# Generated by Django 5.2 on 2025-08-28 22:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_footermenu_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='content',
            field=wagtail.fields.StreamField([('text', 0), ('image', 3), ('full_width_image', 3), ('section', 8), ('grid_card_section', 12), ('heading_text', 13), ('table', 15), ('accordion', 19), ('simple_dropdown', 21)], blank=True, block_lookup={0: ('core.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 5: ('core.blocks.TextBlock', (), {'required': True}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 8: ('wagtail.blocks.StructBlock', [[('heading', 4), ('text', 5), ('image', 6), ('image_position', 7)]], {}), 9: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'features': ['link'], 'help_text': 'A link that this card will point to.', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('heading', 4), ('text', 5), ('image', 1), ('url', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 4), ('grid_cards', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('heading', 4), ('text', 5)]], {}), 14: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'colHeaders': False, 'rowHeaders': False, 'startCols': 3, 'startRows': 3}}), 15: ('wagtail.blocks.StructBlock', [[('table_data', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accordion title', 'max_length': 100, 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('heading', 4), ('content', 5)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'help_text': 'List of accordion items'}), 19: ('wagtail.blocks.StructBlock', [[('title', 16), ('items', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Dropdown title', 'max_length': 100, 'required': True}), 21: ('wagtail.blocks.StructBlock', [[('heading', 20), ('content', 5)]], {})}, help_text='Add and arrange content blocks to build the page.'),
        ),
    ]
