name: Build and Publish On Prem Docker Images

on:
  push:
    branches:
      - develop

jobs:
  build-and-publish-onprem-backend:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push backend Docker image
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: backend
          file: backend/Dockerfile.onprem
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/onprem-backend:latest
            ghcr.io/${{ github.repository }}/onprem-backend:${{ github.sha }}

  build-and-publish-onprem-frontend:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push frontend Docker image
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: frontend
          file: frontend/Dockerfile.onprem
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/onprem-frontend:latest
            ghcr.io/${{ github.repository }}/onprem-frontend:${{ github.sha }}
          build-args: |
            AEROCODE_ONPREM_NEXT_PUBLIC_GRAPHQL_URL=${{ secrets.AEROCODE_ONPREM_NEXT_PUBLIC_GRAPHQL_URL }}
            AEROCODE_ONPREM_GRAPHQL_URL=${{ secrets.AEROCODE_ONPREM_GRAPHQL_URL }}
            AEROCODE_ONPREM_NEXT_PUBLIC_STORAGE_URL=${{ secrets.AEROCODE_ONPREM_NEXT_PUBLIC_STORAGE_URL }}
