name: Build and Publish Docker Images

on:
  push:
    branches:
      - develop

jobs:
  build-and-publish-test-backend:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push backend Docker image
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: backend
          file: backend/Dockerfile.test
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/test-backend:latest
            ghcr.io/${{ github.repository }}/test-backend:${{ github.sha }}
          build-args: |
            AEROCODE_TEST_STORAGE_ACCOUNT_NAME=${{ secrets.AEROCODE_TEST_STORAGE_ACCOUNT_NAME }}
            AEROCODE_TEST_STORAGE_ACCOUNT_KEY=${{ secrets.AEROCODE_TEST_STORAGE_ACCOUNT_KEY }}

  build-and-publish-test-frontend:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push frontend Docker image
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: frontend
          file: frontend/Dockerfile.test
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/test-frontend:latest
            ghcr.io/${{ github.repository }}/test-frontend:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_GRAPHQL_URL=${{ secrets.NEXT_PUBLIC_GRAPHQL_URL }}
            GRAPHQL_URL=${{ secrets.TEST_GRAPHQL_URL }}
