name: Build and Publish Docker Image

on:
  push:
    branches:
      - containerize

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}      
          
      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: backend
          file: backend/Dockerfile
          push: true          
          tags: |
            ghcr.io/flysolomons/website/backend:latest
            ghcr.io/flysolomons/website/backend:${{ github.sha }}